import { z } from 'zod';

export const FeatureSchema = z.object({
  name: z.string(),
  status: z.enum(['available', 'missing', 'partial']),
  details: z.string().optional(),
});

export const PricingTierSchema = z.object({
  name: z.string(),
  price: z.string(),
  period: z.enum(['monthly', 'yearly', 'one-time', 'custom', 'free']),
});

export const CompetitorSchema = z.object({
  name: z.string(),
  website: z.string(),
  description: z.string(),
  features: z.array(FeatureSchema),
  pricing: z.array(PricingTierSchema),
  targetAudience: z.string(),
  positioning: z.string(),
  valueProposition: z.string(),
  strengths: z.array(z.string()),
  weaknesses: z.array(z.string()),
  marketShare: z.string().optional(),
  confidenceScore: z.number().min(0).max(100),
  evidenceType: z.enum(['verified', 'ai_inferred', 'assumption']),
  sources: z.array(z.string()),
});

export const FeatureComparisonRowSchema = z.object({
  featureName: z.string(),
  ourProduct: z.boolean(),
  competitors: z.record(z.string(), z.boolean()),
});

export const FeatureComparisonSchema = z.object({
  rows: z.array(FeatureComparisonRowSchema),
  competitorNames: z.array(z.string()),
});

export const MarketInsightSchema = z.object({
  title: z.string(),
  description: z.string(),
  confidenceScore: z.number().min(0).max(100),
  evidenceType: z.enum(['verified', 'ai_inferred', 'assumption']),
  sources: z.array(z.string()),
});

export const RecommendationSchema = z.object({
  id: z.string(),
  category: z.enum(['product', 'market', 'sales']),
  title: z.string(),
  description: z.string(),
  reasoning: z.string(),
  priority: z.enum(['high', 'medium', 'low']),
});

export const LeadSchema = z.object({
  companyName: z.string(),
  website: z.string(),
  industry: z.string(),
  employeeSize: z.string(),
  location: z.string(),
  contactPerson: z.string(),
  jobTitle: z.string(),
  linkedin: z.string().optional(),
  email: z.string().optional(),
  additionalInfo: z.string().optional(),
  confidenceScore: z.number().min(0).max(100),
  sources: z.array(z.string()),
});

export const DashboardDataSchema = z.object({
  whatToBuildNext: z.array(
    z.object({
      featureName: z.string(),
      reasoning: z.string(),
      impact: z.enum(['high', 'medium', 'low']),
    })
  ).length(5), // Top 5
  biggestThreats: z.array(
    z.object({
      competitorName: z.string(),
      threatLevel: z.enum(['critical', 'high', 'medium', 'low']),
      reasoning: z.string(),
    })
  ).length(5), // Top 5
  leadsToContactFirst: z.array(
    z.object({
      companyName: z.string(),
      contactPerson: z.string(),
      jobTitle: z.string(),
      reasonToContact: z.string(),
    })
  ).length(5), // Top 5
  missingOpportunities: z.array(
    z.object({
      title: z.string(),
      description: z.string(),
      potentialValue: z.string(),
    })
  ).length(5), // Top 5
  actionsToday: z.array(
    z.object({
      task: z.string(),
      priority: z.enum(['high', 'medium', 'low']),
      context: z.string(),
    })
  ),
});

// Complete raw analysis schema generated by Groq
export const AnalysisResultPayloadSchema = z.object({
  competitors: z.array(CompetitorSchema),
  featureComparison: FeatureComparisonSchema,
  marketInsights: z.array(MarketInsightSchema),
  recommendations: z.array(RecommendationSchema),
  leads: z.array(LeadSchema),
  dashboard: DashboardDataSchema,
});
